# Generated by Django 3.2.10 on 2022-09-24 23:56

import authentication.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220925_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_location', models.CharField(blank=True, max_length=150, null=True)),
                ('balance', models.FloatField(default=0, validators=[authentication.validators.minimum_amount])),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='agent_location',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
